// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Chat struct {
	ChatID        int64     `json:"chat_id"`
	LastMessageID *int64    `json:"last_message_id"`
	CreatedAt     time.Time `json:"created_at"`
}

type ChatParticipant struct {
	ChatID            int64              `json:"chat_id"`
	UserID            int64              `json:"user_id"`
	IsTyping          bool               `json:"is_typing"`
	TypingUpdatedAt   pgtype.Timestamptz `json:"typing_updated_at"`
	LastReadMessageID *int64             `json:"last_read_message_id"`
	LastReadAt        pgtype.Timestamptz `json:"last_read_at"`
}

type FriendRequest struct {
	RequestID  int64 `json:"request_id"`
	SenderID   int64 `json:"sender_id"`
	ReceiverID int64 `json:"receiver_id"`
}

type Message struct {
	MessageID  int64     `json:"message_id"`
	SenderID   int64     `json:"sender_id"`
	ChatID     int64     `json:"chat_id"`
	CreatedAt  time.Time `json:"created_at"`
	CypherText []byte    `json:"cypher_text"`
}

type User struct {
	UserID       int64     `json:"user_id"`
	DisplayName  string    `json:"display_name"`
	PasswordHash string    `json:"password_hash"`
	FirstName    string    `json:"first_name"`
	PfpUrl       *string   `json:"pfp_url"`
	LastName     string    `json:"last_name"`
	CreatedAt    time.Time `json:"created_at"`
}

type UserFriendship struct {
	UserID       int64     `json:"user_id"`
	FriendID     int64     `json:"friend_id"`
	FriendshipTs time.Time `json:"friendship_ts"`
}
