// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    display_name,
    first_name,
    last_name,
    password_hash,
    pfp_url
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING user_id, display_name, pfp_url
`

type CreateUserParams struct {
	DisplayName  string  `json:"display_name"`
	FirstName    string  `json:"first_name"`
	LastName     string  `json:"last_name"`
	PasswordHash string  `json:"password_hash"`
	PfpUrl       *string `json:"pfp_url"`
}

type CreateUserRow struct {
	UserID      int64   `json:"user_id"`
	DisplayName string  `json:"display_name"`
	PfpUrl      *string `json:"pfp_url"`
}

// CreateUser
//
//	INSERT INTO users (
//	    display_name,
//	    first_name,
//	    last_name,
//	    password_hash,
//	    pfp_url
//	) VALUES (
//	    $1, $2, $3, $4, $5
//	)
//	RETURNING user_id, display_name, pfp_url
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.DisplayName,
		arg.FirstName,
		arg.LastName,
		arg.PasswordHash,
		arg.PfpUrl,
	)
	var i CreateUserRow
	err := row.Scan(&i.UserID, &i.DisplayName, &i.PfpUrl)
	return i, err
}

const findUserByDisplayName = `-- name: FindUserByDisplayName :one
SELECT user_id, password_hash, first_name, last_name, pfp_url FROM users
WHERE display_name = $1
`

type FindUserByDisplayNameParams struct {
	DisplayName string `json:"display_name"`
}

type FindUserByDisplayNameRow struct {
	UserID       int64   `json:"user_id"`
	PasswordHash string  `json:"password_hash"`
	FirstName    string  `json:"first_name"`
	LastName     string  `json:"last_name"`
	PfpUrl       *string `json:"pfp_url"`
}

// FindUserByDisplayName
//
//	SELECT user_id, password_hash, first_name, last_name, pfp_url FROM users
//	WHERE display_name = $1
func (q *Queries) FindUserByDisplayName(ctx context.Context, arg FindUserByDisplayNameParams) (FindUserByDisplayNameRow, error) {
	row := q.db.QueryRow(ctx, findUserByDisplayName, arg.DisplayName)
	var i FindUserByDisplayNameRow
	err := row.Scan(
		&i.UserID,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.PfpUrl,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT display_name, first_name, last_name, pfp_url FROM users
WHERE user_id = $1
`

type FindUserByIDParams struct {
	UserID int64 `json:"user_id"`
}

type FindUserByIDRow struct {
	DisplayName string  `json:"display_name"`
	FirstName   string  `json:"first_name"`
	LastName    string  `json:"last_name"`
	PfpUrl      *string `json:"pfp_url"`
}

// FindUserByID
//
//	SELECT display_name, first_name, last_name, pfp_url FROM users
//	WHERE user_id = $1
func (q *Queries) FindUserByID(ctx context.Context, arg FindUserByIDParams) (FindUserByIDRow, error) {
	row := q.db.QueryRow(ctx, findUserByID, arg.UserID)
	var i FindUserByIDRow
	err := row.Scan(
		&i.DisplayName,
		&i.FirstName,
		&i.LastName,
		&i.PfpUrl,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT user_id, display_name, password_hash, first_name, pfp_url, last_name, created_at FROM users
ORDER BY display_name
`

// ListUsers
//
//	SELECT user_id, display_name, password_hash, first_name, pfp_url, last_name, created_at FROM users
//	ORDER BY display_name
func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.DisplayName,
			&i.PasswordHash,
			&i.FirstName,
			&i.PfpUrl,
			&i.LastName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPfp = `-- name: UpdateUserPfp :exec
UPDATE users
SET pfp_url = $1
WHERE user_id = $2
`

type UpdateUserPfpParams struct {
	PfpUrl *string `json:"pfp_url"`
	UserID int64   `json:"user_id"`
}

// UpdateUserPfp
//
//	UPDATE users
//	SET pfp_url = $1
//	WHERE user_id = $2
func (q *Queries) UpdateUserPfp(ctx context.Context, arg UpdateUserPfpParams) error {
	_, err := q.db.Exec(ctx, updateUserPfp, arg.PfpUrl, arg.UserID)
	return err
}
